import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { registerAppTool } from "@modelcontextprotocol/ext-apps/server";
import { uiMeta } from "./app.js";
import type { RentADriverClient } from "./client.js";

const Stop = z.object({
  address: z.string().describe("Street address (geocoded if lat/lng omitted)").optional(),
  lat: z.number().optional(), lng: z.number().optional(),
  contact_name: z.string().optional(), contact_phone: z.string().optional(),
  instructions: z.string().optional().describe("Access notes, buzzer, floor, where to leave it"),
  window_start: z.string().optional().describe("ISO datetime"), window_end: z.string().optional().describe("ISO datetime"),
  proof_required: z.array(z.enum(["photo", "signature", "recipient_name", "otp"])).optional(),
});
const Item = z.object({
  description: z.string(), quantity: z.number().int().min(1).default(1),
  size_class: z.enum(["S", "M", "L", "XL"]).default("M").describe("S envelope/bag · M shoebox–backpack · L suitcase · XL bulky parcel (courier weight limits still apply)"),
  weight_kg: z.number().positive().max(20).optional().describe("Weight per package in kg; standard courier limit 20 kg per package, 200 kg combined"), length_cm:z.number().positive().max(1000).optional(),width_cm:z.number().positive().max(1000).optional(),height_cm:z.number().positive().max(1000).optional(), value_cents: z.number().int().optional(),
  category: z.enum(["parcel", "document", "retail", "food", "grocery", "flowers", "pharmacy", "keys", "electronics", "other"]).default("parcel"),
  fragile: z.boolean().default(false),
});
const Contingency = z.object({
  if_no_answer: z.enum(["wait_then_leave_safe", "wait_then_return", "call_client", "leave_with_neighbour"]).optional(),
  if_closed: z.enum(["return_to_pickup", "hold_and_retry", "call_client"]).optional(),
  max_wait_minutes: z.number().int().optional(), return_to: z.string().optional(), notes: z.string().optional(),
}).optional();

type ToolResult = { content: Array<{ type: "text"; text: string }>; structuredContent?: Record<string, unknown>; isError?: boolean };
const ok = (data: unknown): ToolResult => ({ content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: (typeof data === "object" && data ? data : { result: data }) as Record<string, unknown> });
const fail = (e: unknown): ToolResult => {
  const err = e as Error & { code?: string; status?: number; details?: unknown; body?: unknown };
  const hint = err.code === "workspace_required" ? " → call list_country_workspaces, then enable_country_workspace for the pickup country. Fund that local wallet before booking." : err.code === "insufficient_funds" ? " → call create_wallet_deposit (card) or create_x402_deposit (USDC), then fund_delivery." : err.code === "outside_coverage" ? " → call list_service_areas / check_coverage." : err.code === "unauthorized" || err.code === "invalid_api_key" ? " → set RENTADRIVER_API_KEY or call signup." : "";
  return { content: [{ type: "text", text: `Error ${err.code ?? err.status ?? ""}: ${err.message}${hint}${err.details ? "\n" + JSON.stringify(err.details) : ""}` }], isError: true };
};
const run = async (fn: () => Promise<unknown>): Promise<ToolResult> => { try { return ok(await fn()); } catch (e) { return fail(e); } };

export function registerTools(server: McpServer, api: RentADriverClient, opts: { hide?: ReadonlySet<string> } = {}) {
  // Every tool advertises all four hints as explicit booleans. The per-tool justification submitted to OpenAI is
  // ../chatgpt/tool-annotations.md; change both together (a repository test pins them).
  // readOnly    = changes nothing the user can see or must undo. Quotes store a 15-minute pricing snapshot that
  //               charges nothing and is only used if a later create_delivery references it, so they are read-only.
  // destructive = moves or holds real money, deletes/deactivates something, or overwrites earlier values.
  //               Additive records (a message, a rating, a dispute ticket) are not destructive.
  // openWorld   = reaches people or systems outside the caller's own account: dispatching a real independent
  //               driver, messaging or paying that driver, an on-chain payment, or calling a caller-supplied URL.
  //               Lookups against our own service data are bounded, even when an address is geocoded.
  // idempotent  = repeating the same call leaves the same end state.
  const READ_ONLY = new Set(["check_coverage", "list_service_areas", "get_quote", "list_intercity_lanes", "get_intercity_quote", "get_platform_stats", "list_country_workspaces", "check_account_status", "get_wallet_balance", "list_api_keys", "get_delivery", "list_deliveries", "track_delivery", "get_delivery_events", "get_delivery_messages", "get_proof_of_delivery", "list_shopify_orders", "list_store_orders", "list_webhooks"]);
  const DESTRUCTIVE = new Set(["set_spending_controls", "revoke_api_key", "create_delivery", "create_store_pickup", "create_batch", "fund_delivery", "create_recipient_code", "update_delivery", "cancel_delivery", "create_return", "confirm_delivery", "tip_driver", "book_shopify_order", "book_store_order", "delete_webhook"]);
  const OPEN_WORLD = new Set(["create_x402_deposit", "create_delivery", "create_store_pickup", "create_batch", "fund_delivery", "create_return", "send_message_to_driver", "confirm_delivery", "tip_driver", "book_shopify_order", "book_store_order", "register_webhook"]);
  const IDEMPOTENT = new Set(["set_spending_controls", "revoke_api_key", "update_delivery", "rate_driver", "enable_country_workspace", "confirm_delivery", "delete_webhook"]);
  // Tools hidden from THIS server instance. In --http mode index.ts passes a per-request set (Claude-family
  // clients lose create_x402_deposit by default — Claude's connectors directory rejects cryptocurrency
  // transfers); stdio falls back to the MCP_HIDE_TOOLS env (comma list). A hide is a serving decision, not a
  // tool-set change — mcp-tools.ts stays canonical and mcp:check still counts every registration below.
  const HIDDEN = opts.hide ?? new Set((process.env.MCP_HIDE_TOOLS ?? "").split(",").map((s) => s.trim()).filter(Boolean));
  const register = server.registerTool.bind(server);
  server.registerTool = ((name: string, config: { title?: string; annotations?: Record<string, unknown> }, cb: unknown) => {
    const readOnly = READ_ONLY.has(name);
    const annotations = { title: config.title, readOnlyHint: readOnly, destructiveHint: DESTRUCTIVE.has(name), idempotentHint: readOnly || IDEMPOTENT.has(name), openWorldHint: OPEN_WORLD.has(name), ...(config.annotations ?? {}) };
    const tool = register(name, { ...config, annotations } as never, cb as never);
    if (HIDDEN.has(name)) tool.remove();
    return tool;
  }) as typeof server.registerTool;
  // ---- discovery (no auth) ----
  server.registerTool("check_coverage", { title: "Check coverage", description: "Is an address or lat/lng inside a RentADriver service area? Free, no API key.", inputSchema: { address: z.string().optional(), lat: z.number().optional(), lng: z.number().optional() } },
    async (a) => run(() => api.get("/v1/coverage", { address: a.address, lat: a.lat, lng: a.lng }, false)));
  server.registerTool("list_service_areas", { title: "List service areas", description: "Launch cities with currency, timezone and radius. Free.", inputSchema: {} },
    async () => run(() => api.get("/v1/service-areas", {}, false)));
  registerAppTool(server, "get_quote", { _meta: uiMeta("quote"), title: "Get a delivery quote", description: "Price and conditional ETA for a pickup and one or more drop-offs. Null ETA means driver availability is unconfirmed; never promise a pickup time. Free, no key. Returns a quote_id valid 15 minutes; pass it to create_delivery.", inputSchema: { workspace_id: z.string().uuid().optional(), pickup: Stop, dropoffs: z.array(Stop).min(1).max(8), items: z.array(Item).optional(), urgency: z.enum(["asap", "today", "scheduled"]).default("asap"), scheduled_at: z.string().optional(), vehicle_class: z.enum(["bike", "scooter", "car", "suv", "van", "truck"]).optional(), service: z.enum(["auto", "local", "intercity"]).default("auto").describe("intercity = same-day delivery to a neighbouring launch city up to 160 km by road; auto picks it when the drop-off is in one") } },
    async (a) => run(() => api.post("/v1/quotes", a, false)));
  server.registerTool("list_intercity_lanes", { title: "Intercity lanes", description: "Same-day city-to-city routes: for every launch city, the neighbouring launch cities within 160 km by road (e.g. London → Reading, Leeds → Sheffield, San Francisco → San Jose) with road distance, drive time and a same-day sample price. Longer trips are not offered. Free.", inputSchema: {} }, async () => run(() => api.get("/v1/intercity/lanes")));
  server.registerTool("get_intercity_quote", { title: "Intercity quote", description: "Price a same-day delivery to a neighbouring city: pickup in a launch city, drop-off in (or within 20 km of) another launch city in the same country at most 160 km away by road. One dedicated driver collects within about an hour; it must arrive by 21:00 local time, otherwise pickup moves to the next morning. Longer trips return too_far (a parcel network is cheaper). Returns quote_id, the price breakdown incl. the drive-back allowance, and pickup/arrival times. Free, no key.", inputSchema: { workspace_id: z.string().uuid().optional(), pickup: Stop, dropoffs: z.array(Stop).min(1).max(3), items: z.array(Item).optional(), scheduled_at: z.string().optional(), vehicle_class: z.enum(["car", "suv", "van", "truck"]).optional() } },
    async (a) => run(() => api.post("/v1/quotes", { ...a, service: "intercity" })));
  server.registerTool("get_platform_stats", { title: "Platform stats", description: "Live counts: active drivers, drivers on shift, deliveries, agents connected.", inputSchema: {} },
    async () => run(() => api.get("/v1/stats", {}, false)));

  // ---- account ----
  server.registerTool("list_country_workspaces", { title: "Country workspaces", description: "List enabled country workspaces, their separate local-currency balances, and available countries. No FX or balance transfers.", inputSchema: {} }, async () => run(() => api.get("/v1/workspaces")));
  server.registerTool("enable_country_workspace", { title: "Enable country workspace", description: "Enable another delivery country in this account. Admin role required. Starts with zero local-currency balance; existing money stays untouched. Set spending controls independently for this workspace.", inputSchema: { country_code: z.enum(["US","GB","AU","CA"]), spending_cap_per_delivery_cents: z.number().int().min(0).nullable().optional(), daily_cap_cents: z.number().int().min(0).nullable().optional() } }, async (a) => run(() => api.post("/v1/workspaces", a)));
  server.registerTool("signup", { title: "Create account + API key", description: "Self-serve signup for an agent/app. Returns an API key ONCE. Save it as RENTADRIVER_API_KEY. Rehearse with a sandbox (rd_test_) key; live bookings need a funded wallet.", inputSchema: { country_code: z.enum(["US","GB","AU","CA"]).default("US").describe("Initial country workspace. Enable additional countries with enable_country_workspace; each has its own local-currency balance."), name: z.string(), email: z.string().email(), kind: z.enum(["agent", "app", "business"]).default("agent"), agent_framework: z.string().optional() } },
    async (a) => run(() => api.post("/v1/signup", a, false)));
  server.registerTool("check_account_status", { title: "Account status", description: "Confirms the API key works; returns balance, caps and capabilities.", inputSchema: {} },
    async () => api.hasKey ? run(() => api.get("/v1/account")) : ok({ apiKeyConfigured: false, canQuote: true, canCreateDeliveries: false, hint: "Set RENTADRIVER_API_KEY or call signup" }));
  server.registerTool("get_wallet_balance", { title: "Wallet balance", description: "Selected country balance and ledger. Omit workspace_id for the original default wallet.", inputSchema: { workspace_id: z.string().uuid().optional() } }, async (a) => run(() => api.get("/v1/wallet", a)));
  server.registerTool("create_wallet_deposit", { title: "Deposit by card", description: "Creates a Stripe Checkout URL a human must open to pay. Wallet is credited on payment.", inputSchema: { workspace_id: z.string().uuid().optional(), amount_cents: z.number().int().min(500) } },
    async (a) => run(() => api.post("/v1/wallet/deposit", a)));
  server.registerTool("create_x402_deposit", { title: "Deposit USDC (x402)", description: "Agent-native funding: returns x402 v2 payment requirements (USDC on Base). Sign with an x402 client and re-call with the X-Payment header via the REST endpoint.", inputSchema: { workspace_id: z.string().uuid().optional(), amount_cents: z.number().int().min(100) } },
    async (a) => { try { return ok(await api.post(`/v1/x402/wallet/deposit${a.workspace_id ? `?workspace_id=${a.workspace_id}` : ""}`, { amountCents: a.amount_cents })); } catch (e) { const err = e as { status?: number; body?: unknown }; if (err.status === 402) return ok({ payment_required: true, endpoint: `${api.apiUrl}/v1/x402/wallet/deposit${a.workspace_id ? `?workspace_id=${a.workspace_id}` : ""}`, requirements: err.body }); return fail(e); } });
  server.registerTool("set_spending_controls", { title: "Spending controls", description: "Cap per-delivery and rolling 24-hour spend in workspace currency minor units. Zero blocks, null clears. Defaults to original workspace.", inputSchema: { workspace_id: z.string().uuid().optional(), spending_cap_per_delivery_cents: z.number().int().nullable().optional(), daily_cap_cents: z.number().int().nullable().optional() } },
    async (a) => run(() => api.patch(`/v1/account/controls${a.workspace_id ? `?workspace_id=${a.workspace_id}` : ""}`, a)));
  server.registerTool("list_api_keys", { title: "List API keys", description: "Lists the account's API keys with prefix, name, last use and revocation state. Full keys are never returned.", inputSchema: {} }, async () => run(() => api.get("/v1/api-keys")));
  server.registerTool("create_api_key", { title: "Create API key", description: "Issues an additional key (max 10 active) for another agent or environment. The key is shown once.", inputSchema: { name: z.string().optional() } }, async (a) => run(() => api.post("/v1/api-keys", a)));
  server.registerTool("revoke_api_key", { title: "Revoke API key", description: "Permanently deactivates a key. You cannot revoke the key you are calling with.", inputSchema: { key_id: z.string() } }, async (a) => run(() => api.del(`/v1/api-keys/${a.key_id}`)));

  // ---- deliveries ----
  server.registerTool("create_delivery", { title: "Create a delivery", description: "Books a delivery. Pass quote_id from get_quote, or pickup+dropoffs directly. fund=true (default) holds the price from your wallet and starts dispatch. Use dryRun=true first to see the price without committing. Returns next_action.", inputSchema: { workspace_id: z.string().uuid().optional(), dispatch_timeout_hours: z.number().min(0.25).max(72).optional().describe("Search duration in hours, 0.25–72. Default ASAP 24h, otherwise 72h; pickup windows and today deadlines still apply. No repeated funding."), quote_id: z.string().optional(), pickup: Stop.optional(), dropoffs: z.array(Stop).optional(), items: z.array(Item).optional(), urgency: z.enum(["asap", "today", "scheduled"]).optional(), scheduled_at: z.string().optional(), vehicle_class: z.enum(["bike", "scooter", "car", "suv", "van", "truck"]).optional(), service: z.enum(["auto", "local", "intercity"]).optional(), speed: z.enum(["express", "standard", "shared"]).optional(), instructions: z.string().optional(), contingency: Contingency, external_ref: z.string().optional(), idempotency_key: z.string().optional(), webhook_url: z.string().url().optional(), metadata: z.record(z.unknown()).optional(), fund: z.boolean().default(true), dryRun: z.boolean().default(false) } },
    async (a) => run(() => api.post("/v1/deliveries", a)));
  server.registerTool("create_store_pickup", { title: "Store pickup + delivery", description: "Shortcut for the most common agent job: collect a prepaid order from a store and deliver it. Pickup contact gets the order reference in the instructions.", inputSchema: { workspace_id: z.string().uuid().optional(), store_address: z.string(), order_reference: z.string(), store_phone: z.string().optional(), dropoff_address: z.string(), recipient_name: z.string().optional(), recipient_phone: z.string().optional(), item_description: z.string().default("Prepaid order"), size_class: z.enum(["S", "M", "L", "XL"]).default("M"), instructions: z.string().optional(), dryRun: z.boolean().default(false) } },
    async (a) => run(() => api.post("/v1/deliveries", { workspace_id: a.workspace_id, pickup: { address: a.store_address, contact_phone: a.store_phone, instructions: `Collect prepaid order ${a.order_reference}. Check the contents before leaving.` }, dropoffs: [{ address: a.dropoff_address, contact_name: a.recipient_name, contact_phone: a.recipient_phone, instructions: a.instructions, proof_required: ["photo", "recipient_name"] }], items: [{ description: `${a.item_description} (order ${a.order_reference})`, size_class: a.size_class, category: "retail" }], external_ref: a.order_reference, fund: true, dryRun: a.dryRun })));
  server.registerTool("create_batch", { title: "Create several deliveries", description: "Up to 25 create_delivery payloads in one call.", inputSchema: { deliveries: z.array(z.record(z.unknown())).min(1).max(25) } }, async (a) => run(() => api.post("/v1/deliveries/batch", a)));
  server.registerTool("fund_delivery", { title: "Fund a delivery", description: "For deliveries created with fund=false, or after topping up the wallet.", inputSchema: { delivery_id: z.string() } }, async (a) => run(() => api.post(`/v1/deliveries/${a.delivery_id}/fund`)));
  registerAppTool(server, "get_delivery", { title: "Get delivery", description: "Full delivery by id or short code (RD-XXXXXXX). Hosts that support MCP Apps render a live tracker card.", inputSchema: { delivery_id: z.string() }, _meta: uiMeta("delivery") }, async (a) => run(() => api.get(`/v1/deliveries/${a.delivery_id}`)));
  server.registerTool("list_deliveries", { title: "List deliveries", description: "status='active' or a comma list; since ISO datetime.", inputSchema: { status: z.string().optional(), since: z.string().optional(), limit: z.number().int().max(100).optional(), offset: z.number().int().optional() } }, async (a) => run(() => api.get("/v1/deliveries", a)));
  server.registerTool("create_recipient_code", {title:"Create a private handover code",description:"Generate or replace a six-digit code for a delivery stop requiring OTP proof. Share it privately with the intended recipient, never the driver. Replacing invalidates the old code. Expires in seven days; five failed attempts lock it.",inputSchema:{delivery_id:z.string().uuid(),stop_id:z.string().uuid()}},async a=>run(()=>api.post(`/v1/deliveries/${a.delivery_id}/stops/${a.stop_id}/code`,{})));
  server.registerTool("track_delivery", { title: "Track delivery", description: "Live status, ETA, driver position and last event. Poll this every 30–60s while active.", inputSchema: { delivery_id: z.string() } }, async (a) => run(() => api.get(`/v1/deliveries/${a.delivery_id}/track`)));
  server.registerTool("get_delivery_events", { title: "Delivery timeline", description: "Every event on the delivery in order: created, funded, dispatching, offers, assigned, each driver step, delivered, confirmed, paid, plus messages.", inputSchema: { delivery_id: z.string() } }, async (a) => run(() => api.get(`/v1/deliveries/${a.delivery_id}/events`)));
  server.registerTool("update_delivery", { title: "Update delivery", description: "Change instructions, contingency rules or the drop-off contact while in progress.", inputSchema: { delivery_id: z.string(), instructions: z.string().optional(), contingency: Contingency, dropoff_contact: z.object({ contact_name: z.string().optional(), contact_phone: z.string().optional() }).optional(), window_end: z.string().optional(), metadata: z.record(z.unknown()).optional() } },
    async ({ delivery_id, ...rest }) => run(() => api.patch(`/v1/deliveries/${delivery_id}`, rest)));
  server.registerTool("cancel_delivery", { title: "Cancel delivery", description: "Free before a driver is assigned; a cancellation fee after assignment; not possible after pickup.", inputSchema: { delivery_id: z.string(), reason: z.string().optional() } }, async (a) => run(() => api.post(`/v1/deliveries/${a.delivery_id}/cancel`, { reason: a.reason })));
  server.registerTool("create_return", { title: "Return leg", description: "Create the reverse delivery (last drop-off back to pickup).", inputSchema: { delivery_id: z.string() } }, async (a) => run(() => api.post(`/v1/deliveries/${a.delivery_id}/return`)));

  // ---- driver comms ----
  server.registerTool("send_message_to_driver", { title: "Message the driver", description: "Delivered as a push + in-app message once a driver is assigned.", inputSchema: { delivery_id: z.string(), body: z.string().max(2000) } }, async (a) => run(() => api.post(`/v1/deliveries/${a.delivery_id}/messages`, { body: a.body })));
  server.registerTool("get_delivery_messages", { title: "Read messages", description: "The full message thread between you and the driver for one delivery, oldest first.", inputSchema: { delivery_id: z.string() } }, async (a) => run(() => api.get(`/v1/deliveries/${a.delivery_id}/messages`)));

  // ---- proof + settlement ----
  server.registerTool("get_proof_of_delivery", { title: "Proof of delivery", description: "Signed photo URLs (1h), signature, recipient name, geo + time.", inputSchema: { delivery_id: z.string() } }, async (a) => run(() => api.get(`/v1/deliveries/${a.delivery_id}/proof`)));
  server.registerTool("confirm_delivery", { title: "Confirm delivery", description: "Releases payment to the driver. Auto-confirms 24h after delivery if you don't.", inputSchema: { delivery_id: z.string() } }, async (a) => run(() => api.post(`/v1/deliveries/${a.delivery_id}/confirm`)));
  server.registerTool("open_dispute", { title: "Open a dispute", description: "Funds stay held; ops reviews within 24h.", inputSchema: { delivery_id: z.string(), reason: z.string().min(5), evidence: z.array(z.string().url()).optional() } }, async (a) => run(() => api.post(`/v1/deliveries/${a.delivery_id}/dispute`, { reason: a.reason, evidence: a.evidence ?? [] })));
  server.registerTool("tip_driver", { title: "Tip the driver", description: "Cents, from your wallet. Reuse idempotency_key when retrying the same tip.", inputSchema: { delivery_id: z.string(), idempotency_key: z.string().min(8).max(100), amount_cents: z.number().int().min(50).max(50000) } }, async (a) => run(() => api.post(`/v1/deliveries/${a.delivery_id}/tip`, { amount_cents: a.amount_cents, idempotency_key: a.idempotency_key })));
  server.registerTool("rate_driver", { title: "Rate the driver", description: "Rate the driver of a completed delivery from 1 to 5 stars, with an optional comment.", inputSchema: { delivery_id: z.string(), stars: z.number().int().min(1).max(5), comment: z.string().optional() } }, async (a) => run(() => api.post(`/v1/deliveries/${a.delivery_id}/rate`, { stars: a.stars, comment: a.comment })));

  // ---- Shopify (store must have the RentADriver app installed) ----
  server.registerTool("list_shopify_orders", { title: "List Shopify orders", description: "Orders the RentADriver app for Shopify has seen on the shops connected to this account, with the booking status (booked / skipped / needs_funds / failed) and the linked delivery. Requires the app to be installed on the store: https://rentadriver.ai/integrations/shopify", inputSchema: { status: z.enum(["pending", "skipped", "booked", "needs_funds", "failed", "cancelled"]).optional(), limit: z.number().int().max(200).optional() } }, async (a) => run(() => api.get("/v1/shopify/orders", a)));
  server.registerTool("book_shopify_order", { title: "Book a Shopify order", description: "Book a same-day delivery for a Shopify order by its name (e.g. #1042) or id. Pickup is the store location, drop-off the order's shipping address, items from the line items. Fetches the order from Shopify if the app has not seen it. force=true ignores the shop's radius and size limits. On success the order is fulfilled with a tracking link as the driver picks it up.", inputSchema: { order: z.string().describe("Order name like #1042, Shopify order id, or the app's order row id"), shop: z.string().optional().describe("myshopify.com domain when several shops are connected"), force: z.boolean().default(false) } }, async (a) => run(() => api.post(`/v1/shopify/orders/${encodeURIComponent(a.order)}/book`, { force: a.force, shop: a.shop })));

  // ---- Store connectors: WooCommerce, BigCommerce, Wix Stores, Squarespace (store must be connected at rentadriver.ai/integrations/<platform>) ----
  const Platform = z.enum(["woocommerce", "bigcommerce", "wix", "squarespace"]);
  server.registerTool("list_store_orders", { title: "List store orders", description: "Orders the RentADriver connector has seen on the WooCommerce, BigCommerce, Wix Stores or Squarespace stores connected to this account, with the booking status (booked / skipped / needs_funds / failed) and the linked delivery. Requires the store to be connected: https://rentadriver.ai/integrations/<platform>", inputSchema: { platform: Platform, status: z.enum(["pending", "skipped", "booked", "needs_funds", "failed", "cancelled"]).optional(), limit: z.number().int().max(200).optional() } }, async (a) => run(() => api.get(`/v1/${a.platform}/orders`, { status: a.status, limit: a.limit })));
  server.registerTool("book_store_order", { title: "Book a store order", description: "Book a same-day delivery for a WooCommerce, BigCommerce, Wix Stores or Squarespace order by its number (e.g. #1042) or id. Pickup is the store location, drop-off the order's shipping address, items from the line items. Fetches the order from the platform if the connector has not seen it. force=true ignores the store's radius and size limits. On success the order is marked shipped / fulfilled with a tracking link as the driver picks it up.", inputSchema: { platform: Platform, order: z.string().describe("Order number like #1042, the platform's order id, or the connector's order row id"), store: z.string().optional().describe("Store id, URL or key when several stores of that platform are connected"), force: z.boolean().default(false) } }, async (a) => run(() => api.post(`/v1/${a.platform}/orders/${encodeURIComponent(a.order)}/book`, { force: a.force, store: a.store })));

  // ---- webhooks ----
  server.registerTool("register_webhook", { title: "Register webhook", description: "HMAC-signed POSTs for delivery.* events. Returns the signing secret once.", inputSchema: { url: z.string().url(), events: z.array(z.string()).optional() } }, async (a) => run(() => api.post("/v1/webhooks", a)));
  server.registerTool("list_webhooks", { title: "List webhooks", description: "Active webhooks registered on the account.", inputSchema: {} }, async () => run(() => api.get("/v1/webhooks")));
  server.registerTool("delete_webhook", { title: "Delete webhook", description: "Deactivates a webhook; queued deliveries to it stop.", inputSchema: { webhook_id: z.string() } }, async (a) => run(() => api.del(`/v1/webhooks/${a.webhook_id}`)));
}
